services:
  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "127.0.0.1:8081:80"
      # - "8443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on: []
